examen3/equipos/urls.py
from django.urls import path

from equipos import views


app_name = "equipos"


urlpatterns = [
    path('create_equipo/', views.CreateEquipo.as_view(), name="create_equipo"),
    path('', views.index, name="index"),
    path('list_equipo/', views.ListEquipo.as_view(), name="list_equipo"),
    path('detail_equipo/<int:pk>/', views.DetailEquipo.as_view(), name="detail_equipo"),
    path('update_equipo/<int:pk>/', views.UpdateEquipo.as_view(), name="update_equipo"),
    path('delete_equipo/<int:pk>/', views.delete_equipo, name="delete_equipo"),
]

examen3/estadios/urls.py
from django.urls import path

from estadios import views


app_name = "estadios"


urlpatterns = [
    path('create_estadio/', views.CreateEstadio.as_view(), name="create_estadio"),
    path('list_estadio/', views.ListEstadio.as_view(), name="list_estadio"),
    path('detail_estadio/<int:pk>/', views.DetailEstadio.as_view(), name="detail_estadio"),
    path('update_estadio/<int:pk>/', views.UpdateEstadio.as_view(), name="update_estadio"),
    path('delete_estadio/<int:pk>/', views.delete_estadio, name="delete_estadio"),
]

examen3/examen3/urls.py
from django.contrib import admin
from django.urls import path, include
from equipos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="Index"),
    path('equipos/', include("equipos.urls")),
    path('jugadores/', include("jugadores.urls")),
    path('estadios/', include("estadios.urls")),

]

examen3/jugadores/urls.py
from django.urls import path

from jugadores import views


app_name = "jugadores"


urlpatterns = [
    path('create_jugador/', views.Createjugador.as_view(), name="create_jugador"),
    path('list_jugador/', views.Listjugador.as_view(), name="list_jugador"),
    path('detail_jugador/<int:pk>/', views.Detailjugador.as_view(), name="detail_jugador"),
    path('update_jugador/<int:pk>/', views.Updatejugador.as_view(), name="update_jugador"),
    path('delete_jugador/<int:pk>/', views.delete_jugador, name="delete_jugador"),
]

examen3/equipos/models.py
from django.db import models

# Create your models here.

class Equipo(models.Model):
    Nombre = models.CharField(max_length=32)
    Entrenador = models.CharField(max_length=32)
    Total_de_jugadores = models.IntegerField()
    Total_de_Partidos = models.IntegerField()
    Total_de_puntos = models.IntegerField()
    Clasificado = models.BooleanField(default=False)

    def __str__(self):
        return self.Nombre

examen3/estadios/models.py
from django.db import models

# Create your models here.

class Estadio(models.Model):
    Nombre = models.CharField(max_length=50)
    Capacidad = models.IntegerField()
    Disponible = models.BooleanField()
    Partido_a_disputar = models.CharField(max_length=100)
    Fecha = models.DateField()

    def __str__(self):
        return self.Nombre

examen3/jugadores/models.py
from django.db import models

# Create your models here.

class Jugadore(models.Model):
    Nombre=models.CharField(max_length=50)
    Edad = models.IntegerField()
    Numero = models.IntegerField()
    Equipo_perteneciente = models.CharField(max_length=50)
    Fecha_de_ingreso_al_equipo = models.DateField()
    Estatus = models.BooleanField(default=True)

    def __str__(self):
        return self.Nombre

examen3/equipos/forms.py
from dataclasses import field
from socket import fromshare
from django import forms

from .models import Equipo

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = "__all__"

examen3/estadios/forms.py
from dataclasses import field
from socket import fromshare
from django import forms

from .models import Estadio

class EstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = "__all__"

examen3/jugadores/forms.py
from dataclasses import field
from socket import fromshare
from django import forms

from .models import Jugadore

class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugadore
        fields = "__all__"

examen3/equipos/views.py
from audioop import reverse
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Equipo
from .forms import EquipoForm
# Create your views here.


def index(request):
    context = {
    }
    return render(request, "home/index.html", context)

class CreateEquipo(generic.CreateView):
    template_name = "Equipos/create_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy("equipos:list_equipo")

class ListEquipo(generic.ListView):
    template_name = "Equipos/list_equipos.html"
    queryset = Equipo.objects.filter(Clasificado=True)


class DetailEquipo(generic.DetailView):
    template_name = "equipos/detail_equipo.html"
    model = Equipo


class UpdateEquipo(generic.UpdateView):
    template_name = "equipos/update_equipo.html"
    model = Equipo
    fields = "__all__"
    success_url = reverse_lazy("equipos:list_equipo")



def delete_equipo(request, pk):
    equipo = Equipo.objects.get(pk=pk, Clasificado=True)
    equipo.Clasificado = False
    equipo.save()
    messages.warning(request, "Fuiste descalificado de la temporada :(")
    return redirect("equipos:list_equipo")

examen3/estadios/views.py
from audioop import reverse
from urllib import request
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages


from .models import Estadio
from .forms import EstadioForm
# Create your views here.


class CreateEstadio(generic.CreateView):
    template_name = "Estadios/create_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy("estadios:list_estadio")




class ListEstadio(generic.ListView):
    template_name = "Estadios/list_estadio.html"
    queryset = Estadio.objects.filter(Disponible=True)


class DetailEstadio(generic.DetailView):
    template_name = "estadios/detail_estadio.html"
    model = Estadio


class UpdateEstadio(generic.UpdateView):
    template_name = "estadios/update_estadio.html"
    model = Estadio
    fields = "__all__"
    success_url = reverse_lazy("estadios:list_estadio")



def delete_estadio(request, pk):
    estadio = Estadio.objects.get(pk=pk, Disponible=True)
    estadio.Disponible = False
    estadio.save()
    messages.warning(request, "Fuiste clausurado esta temporada :(")
    return redirect("estadios:list_estadio")

examen3/jugadores/views.py
from audioop import reverse
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Jugadore
from .forms import JugadorForm
# Create your views here.


class Createjugador(generic.CreateView):
    template_name = "jugadores/create_jugador.html"
    model = Jugadore
    form_class = JugadorForm
    success_url = reverse_lazy("jugadores:list_jugador")


class Listjugador(generic.ListView):
    template_name = "jugadores/list_jugador.html"
    queryset = Jugadore.objects.filter(Estatus=True)


class Detailjugador(generic.DetailView):
    template_name = "jugadores/detail_jugador.html"
    model = Jugadore


class Updatejugador(generic.UpdateView):
    template_name = "jugadores/update_jugador.html"
    model = Jugadore
    fields = "__all__"
    success_url = reverse_lazy("jugadores:list_jugador")



def delete_jugador(request, pk):
    jugador = Jugadore.objects.get(pk=pk, Estatus=True)
    jugador.Estatus = False
    jugador.save()
    messages.warning(request, "Fuiste descalificado de la temporada :(")
    return redirect("jugadores:list_jugador")

examen3/templates/Equipos/create_equipo.html
{% extends 'base/base.html' %}

{% block title %}Crear Equipo{% endblock title%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" class="form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success mb-3 form-control">Registrar</button>
                <a href="{% url 'equipos:list_equipo' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
        
            </form>
        </div>
    </div>
</div>

{% endblock  %}

examen3/templates/Equipos/detail_equipo.html
{%extends "base/base.html"%}
{% block title %}Detalles{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip">
                <th>Nombre</th>
                <th>Entrenador</th>
                <th>Total de jugadores</th>
                <th>Total de Partidos</th>
                <th>Total de puntos</th>
                <tr>
                    <td>{{ object.Nombre }}</th>
                    <td>{{ object.Entrenador}}</td>
                    <td>{{ object.Total_de_jugadores}}</td>
                    <td>{{ object.Total_de_Partidos}}</td>
                    <td>{{ object.Total_de_puntos}}</td>
                </tr>
            </table>
            <a href="{% url 'equipos:list_equipo' %}" class = "btn btn-outline-success mb-3 form-control">Regresar</a>

        </div>

    </div>
</div>


{% endblock  %}

examen3/templates/Equipos/list_equipos.html
{% extends 'base/base.html' %}

{% block title %}Lista de Equipos{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip"  style="text-align: center ;">
                <th>Nombre</th>
                <th>Entrenador</th>
                <th>Total de jugadores</th>
                <th>Total de Partidos</th>
                <th>Total de puntos</th>
                <th>Clasificado</th>
                <th>Acciones</th>
                {% for Equipo in object_list %}
                <tr>
                    <td>{{Equipo.Nombre}}</td>
                    <td>{{Equipo.Entrenador}}</td>
                    <td>{{Equipo.Total_de_jugadores}}</td>
                    <td>{{Equipo.Total_de_Partidos}}</td>
                    <td>{{Equipo.Total_de_puntos}}</td>
                    <td>{{Equipo.Clasificado}}</td>
                    <td>
                        <a href="{% url 'equipos:detail_equipo' Equipo.pk %}" class="btn btn-outline-info">Info</a>
                        <a href="{% url 'equipos:update_equipo' Equipo.pk %}" class="btn btn-outline-warning">Actualizacion</a>
                       
                        <a href="{% url 'equipos:delete_equipo' Equipo.pk %}" class="btn btn-outline-danger">Descalificar</a>
                    </td>

                </tr>    
                {% endfor %}
            </table>
            <a href= "{% url 'equipos:create_equipo' %}" class = "btn btn-outline-success mb-3 form-control">Ingresar Nuevo Equipo</a>
        </div>
    </div>
</div>

{% endblock %}

examen3/templates/Equipos/update_equipo.html
{% extends 'base/base.html' %}

{% block tittle %}Actualizacion{% endblock tittle%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-warning mb-3 form-control">Actualizar</button>
                <a href="{% url 'equipos:list_equipo' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
            </form>
        </div>
    </div>
</div>          

{% endblock  %}

examen3/templates/Estadios/create_estadio.html
{% extends 'base/base.html' %}

{% block title %}Crear Estadio{% endblock title%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
        <form action="" method="POST" class="form">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-outline-success mb-3 form-control">Registrar</button>
            <a href="{% url 'estadios:list_estadio' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
    
        </form>
    
        </div>
    </div>
</div>

{% endblock  %}

examen3/templates/Estadios/detail_estadio.html
{%extends "base/base.html"%}
{% block title %}Detalles{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip" >
                <th style="text-align: center ;">Nombre</th>
                <th style="text-align: center ;">Capacidad</th>
                <th style="text-align: center ;">Disponible</th>
                <th style="text-align: center ;">Partido a disputar</th>
                <th style="text-align: center ;">Fecha</th>
                <tr>
                    <td style="text-align: center ;">{{ object.Nombre }}</th>
                    <td style="text-align: center ;">{{ object.Capacidad}}</td>
                    <td style="text-align: center ;">{{ object.Disponible}}</td>
                    <td style="text-align: center ;">{{ object.Partido_a_disputar}}</td>
                    <td style="text-align: center ;">{{ object.Fecha}}</td>
                </tr>

            </table>
            <a href="{% url 'estadios:list_estadio' %}" class = "btn btn-outline-success mb-3 form-control">Regresar</a>
        </div>
    </div>
</div>


{% endblock  %}

examen3/templates/Estadios/list_estadio.html
{% extends 'base/base.html' %}

{% block title %}Lista de estadios{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip" style="text-align: center ;">
                <th>Nombre</th>
                <th>Capacidad</th>
                <th>Disponible</th>
                <th>Partido a disputar</th>
                <th>Fecha</th>
                <th>Acciones</th>
                {% for Estadio in object_list %}
                <tr>
                    <td>{{Estadio.Nombre}}</td>
                    <td>{{Estadio.Capacidad}}</td>
                    <td>{{Estadio.Disponible}}</td>
                    <td>{{Estadio.Partido_a_disputar}}</td>
                    <td>{{Estadio.Fecha}}</td>
                    <td>
                        <a href="{% url 'estadios:detail_estadio' Estadio.pk %}" class="btn btn-outline-info">Info</a>
                        <a href="{% url 'estadios:update_estadio' Estadio.pk %}" class="btn btn-outline-warning">Actualizacion</a>
                        <a href="{% url 'estadios:delete_estadio' Estadio.pk %}" class="btn btn-outline-danger">Deshabilitar</a>
                    </td>
                </tr>    
                {% endfor %}
            </table>
            <a href= "{% url 'estadios:create_estadio' %}" class = "btn btn-outline-success mb-3 form-control">Ingresar Nuevo Estadio</a>
        </div>
    </div>
</div>

{% endblock %}

examen3/templates/Estadios/update_estadio.html
{% extends 'base/base.html' %}

{% block tittle %}Actualizacion{% endblock tittle%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-warning mb-3 form-control">Actualizar</button>
                <a href="{% url 'estadios:list_estadio' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock  %}

examen3/templates/Jugadores/create_jugador.html
{% extends 'base/base.html' %}

{% block title %}Crear Equipo{% endblock title%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" class="form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-outline-success mb-3 form-control">Registrar</button>
                <a href="{% url 'jugadores:list_jugador' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
        
            </form>
        
        </div>
    </div>
</div>
{% endblock  %}

examen3/templates/Jugadores/detail_jugador.html
{%extends "base/base.html"%}
{% block title %}Detalles{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip"  style="text-align: center ;">
                <th>Nombre</th>
                <th>Edad</th>
                <th>Numero</th>
                <th>Equipo Perteneciente</th>
                <th>Fecha de ingreso al equipo</th>
                <tr>
                    <td>{{ object.Nombre }}</th>
                    <td>{{ object.Edad}}</td>
                    <td>{{ object.Numero}}</td>
                    <td>{{ object.Equipo_perteneciente}}</td>
                    <td>{{ object.Fecha_de_ingreso_al_equipo}}</td>
                </tr>
            </table>
            <a href="{% url 'jugadores:list_jugador' %}" class = "btn btn-outline-success mb-3 form-control">Regresar</a>
        </div>

    </div>
</div>


{% endblock  %}

examen3/templates/Jugadores/list_jugador.html
{% extends 'base/base.html' %}

{% block title %}Lista de Jugadores{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <table class="table table-strip"  style="text-align: center ;">
                <th>Nombre</th>
                <th>Edad</th>
                <th>Numero</th>
                <th>Equipo Perteneciente</th>
                <th>Fecha de ingreso</th>
                <th>Estatus</th>
                <th>Acciones</th>
                {% for Jugadore in object_list %}
                <tr>
                    <td>{{Jugadore.Nombre}}</td>
                    <td>{{Jugadore.Edad}}</td>
                    <td>{{Jugadore.Numero}}</td>
                    <td>{{Jugadore.Equipo_perteneciente}}</td>
                    <td>{{Jugadore.Fecha_de_ingreso_al_equipo}}</td>
                    <td>{{Jugadore.Estatus}}</td>
                    <td>
                        <a href="{% url 'jugadores:detail_jugador' Jugadore.pk %}" class="btn btn-outline-info">Info</a>
                        <a href="{% url 'jugadores:update_jugador' Jugadore.pk %}" class="btn btn-outline-warning">Actualizar</a>
                        <a href="{% url 'jugadores:delete_jugador' Jugadore.pk %}" class="btn btn-outline-danger">Descalificar</a>
                </td>

                </tr>    
                {% endfor %}
            </table>
            <a href= "{% url 'jugadores:create_jugador' %}" class = "btn btn-outline-success mb-3 form-control">Ingresar Nuevo jugador</a>
        </div>
    </div>
</div>
{% endblock %}

examen3/templates/Jugadores/update_jugador.html
{% extends 'base/base.html' %}

{% block tittle %}Actualizacion{% endblock tittle%}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-warning mb-3 form-control">Actualizar</button>
                <a href="{% url 'jugadores:list_jugador' %}" class="btn btn-outline-info mb-3 form-control">Cancelar</a>
            </form>
        </div>
    </div>
</div>

{% endblock  %}

examen3/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <script src="{% static 'sweetalert2/sweetalert2.all.min.js'%}"></script>
  </head>
  <body style="background-color: #8B0000;">
    <!--Parte de arriba-->
      <div class="card">
          <h2 style="text-align:center;">PARRA NATIONAL LEAGUE FOOTBALL</h2>
      </div>
    <!--Barrita-->
    <div class="conteiner-fluid">
      <div class="row">
      <nav class="navbar bg-dark navbar-dark navbar-expand-sm">
          <div class="container-fluid">
            <a class="navbar-brand px-3" href="/">PNLF</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
              <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/equipos/list_equipo">Equipos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/jugadores/list_jugador">Jugadores</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/estadios/list_estadio">Estadios</a>
                </li>
              </ul>
            </div>
          </div>
      </nav>
      <!--Termina barrita-->
    </div>
    <div class="row">
      <div class="col-2"></div>
      <div class="col-8">
        {% if messages %}
        {% for message in messages %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <script>
            Swal.fire({
              "title": "Registrado",
              "text": "{{ message }}",
              "icon": "success",
              "confirmButtonText": "OK"
            })
          </script>
          {% endif %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
          <script>
            Swal.fire({
              "title": ":(",
              "text": "{{ message }}",
              "icon": "warning",
              "confirmButtonText": "OK"
            })
          </script>
          {% endif %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <script>
            Swal.fire({
              "title": "ERROR!",
              "text": "{{ message }}",
              "icon": "error",
              "confirmButtonText": "OK"
            })
          </script>
          {% endif %}
        {% endfor %}
      {% endif %}
    


  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    {% block content %}

    {% endblock content %}
  </div>
  <div class="col-2"></div>
</div>
<div class="row">
  <div class="col px-3">
    <footer><font color="white">Hecho por Genaro Damian Martinez Perez</font></footer>
  </div>
</div>
</div>

    <script src="{% static 'js/bootstrap.bundle.min.js'%}" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="{% static 'mensage.js' %}"></script>
  </body>
</html>

examen3/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}PNLF{% endblock title %}

{% block content %}
<div class="col-md-10 offset-md-1">
    <div class="card">
        <div class="card-body">
            <h4 style="text-align: center;">Seleccione de opciones:</h4>
            <form action="/updateTeam/{{team.id_team}}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group py-4 d-grid gap-4 col-md-4 offset-md-4">
                    <td>
                        <a href="/equipos/list_equipo" class="btn btn-danger">Equipos</a>
                        <a href="/jugadores/list_jugador" class="btn btn-danger">Jugadores</a>
                        <a href="/estadios/list_estadio" class="btn btn-danger">Estadios</a>
                    </td>
                </div>
            </form>
        </div>
    </div>    
</div>  
{% endblock content %}